FROM ubuntu:latest

WORKDIR /app

# Change from sh to bash
RUN ln -snf /bin/bash /bin/sh

# Install bun required deps
RUN apt update && apt install curl unzip -y

# Install bun
RUN curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.24"
RUN source /root/.bashrc 

COPY package.json .
COPY . .


# RUN bun install
